{
 "title": "Asus RT-AC68U Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"router\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode='idle', job=\"router\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemFree_bytes{job=\"router\"}/node_memory_MemTotal_bytes{job=\"router\"}",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"router\", device=\"ppp0\"}[5m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"router\", device=\"ppp0\"}[5m])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Ethernet Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"router\", device=\"vlan1\"}[5m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"router\", device=\"vlan1\"}[5m])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "2.4GHz Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"router\", device=\"eth1\"}[5m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"router\", device=\"eth1\"}[5m])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "5GHz Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"router\", device=\"eth2\"}[5m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"router\", device=\"eth2\"}[5m])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "VPN Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"router\", device=\"tun11\"}[5m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"router\", device=\"tun11\"}[5m])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"router\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"router\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"router\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "1 - node_memory_MemFree_bytes{job=\"router\"}/node_memory_MemTotal_bytes{job=\"router\"}",
     "legendFormat": "Used %"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"router\", device=~\"vlan1|eth0|eth1|tun11\"}[5m])",
     "legendFormat": "{{device}} - IN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"router\", device=~\"vlan1|eth0|eth1|tun11\"}[5m])",
     "legendFormat": "{{device}} - OUT"
    }
   ]
  }
 ]
}